- colima
On fresh OSX installs, the `"$HOME/Library/LaunchAgents/"` folder does not exist.
> Ensure LaunchAgents directory exists

- colima
Provisioning a new VM fails to restart after installing docker:
```
[colima] 15:47:01 creating and starting VM ...
[colima] 15:47:54 provisioning VM ...
[colima] 15:47:54 provisioning docker ...
[colima] 15:47:54 provisioning docker in VM ...
[colima] 15:48:45 restarting VM to complete docker setup ...
```
This is because of the following error:
```
time="2021-09-16T15:48:45+03:00" level=info msg="Sending SIGINT to hostagent process 5892"
time="2021-09-16T15:48:45+03:00" level=info msg="Waiting for the host agent and the qemu processes to shut down"
time="2021-09-16T15:48:45+03:00" level=info msg="[hostagent] Received SIGINT, shutting down the host agent"
time="2021-09-16T15:48:46+03:00" level=info msg="[hostagent] Shutting down the host agent"
time="2021-09-16T15:48:46+03:00" level=info …
```
> Sleep between stop and start when provisioning VM

- INSTALL.md
- README.md
Introduced in `nixpkgs` by https://github.com/NixOS/nixpkgs/pull/150282
findable with https://search.nixos.org/packages?channel=unstable&show=colima&from=0&size=50&sort=relevance&type=packages&query=colima.
**Note:** It will take another 5-7 days that package will appeare in `nixpkgs-unstable`. However from than it will be automatically included into the next major nix versions.
> add documenation for installation via nix

- .github/workflows/go.yml
- .gitignore
- Makefile
- environment/container/kubernetes/kubernetes.go
- util/downloader/download.go
- util/terminal/output.go
* Adding GolangCI Lint for linting
* Added lint task to Makefile
* Resolved basic linting issues
* Removed `kubernetesVersion` as it is private and used.  If desired, please indicate how it is to be used 
* `time.Since` is preferred to `time.Now().Sub` otherwise same functionality
* Likely the most controversial, The assignment of `downloadURL := u` was never used.  if err not nil, it is assigned to `u` otherwise an error is returned.  It is better and more readable in Go to not use `else` unless required, in this case, it is much more clear.
Looking forward to adding more linting rules.   I was looking for feedback on this first.
Signed-off-by: Ken Sipe <kensipe@gmail.com
> Add GolangCI Lint

- README.md
`nix-env -i colima` will search through all attrsets in Nixpkgs, whereas `-A nixpkgs.colima` will only look at the top level, which is where the package lives.
Technically on NixOS this would be `nixos.colima`, but NixOS users probably know that all too well.
> Faster nix installation

- INSTALL.md
- README.md
Colima is available on [MacPorts](https://ports.macports.org/port/colima/), so the relevant docs should be updated with installation instructions.
> docs: add documentation for MacPorts installation

- environment/vm/lima/yaml.go
docker: support host.docker.internal hostname
fix #186: 3-part port binding is not respected
> network: fixes for docker/containerd

- cmd/delete.go
- cmd/kubernetes.go
- cmd/list.go
- cmd/nerdctl.go
- cmd/start.go
- cmd/status.go
- cmd/stop.go
- cmd/version.go
I use Colima conveniently every day. Thank you.
When I have multiple profiles, I have deleted the environment several times by running the following command by mistake.
```console
$ colima list
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK
default    Running    aarch64    8       8GiB      128GiB
x64        Running    x86_64     8       8GiB      128GiB
$ # I want to delete `x64` profile !!
$ colima delete x64 # !!!???
are you sure you want to delete colima and all settings? [y/N] y
INFO[0015] deleting colima
INFO[0015] deleting ...                                  context=docker
INFO[0015] deleting ...                                  context=vm
INFO[0015] done
$ colima list 
PROFILE    STATUS     ARCH      CPUS    MEMORY    DISK
x64        Running    x86_64    8       8GiB …
```
> cli: report error if arguments are given for subcommands that require no arguments

- app/app.go
- cmd/delete.go
- cmd/root/root.go
- cmd/ssh-config.go
- cmd/start.go
- cmd/status.go
- cmd/stop.go
- cmd/version.go
- config/config.go
- environment/vm.go
- environment/vm/lima/lima.go
- environment/vm/lima/yaml.go
cli: add `ssh-config` command to view SSH connection configuration.
cli: accept profile name as arg for some commands e.g. `colima start custom` = `colima start --profile=custom`
cli: remove obsolete `--port-interface` flag for `colima start`
> general ux improvements

- environment/vm/lima/network/installer.go
This is unlikely to affect users who install colima from Homebrew
or similar sources but ensures that the `colima-vmnet` symlink
works even if the `colima` binary is not in `PATH`.
> vmnet: resolve to absolute path for symlink/install

- environment/vm/lima/yaml.go
Workaround for failing qemu64 cpu on x86_64 emulation.
> cpu: workaround for broken qemu64

- Makefile
> net: remove CGO_ENABLED=0 to fix VPN connections

- app/app.go
- cmd/start.go
- cmd/start_test.go
- config/config.go
- environment/container/ubuntu/provision.go
- environment/environment.go
- environment/vm/lima/lima.go
- environment/vm/lima/limautil/limautil.go
- environment/vm/lima/yaml.go
- util/util.go
Add support for specifying `mountPoint` for mounted folders, a feature already in Lima but not utilised.
```
colima start --mount /src/folder:/dest/folder:w
```
```yaml
mounts:
- location: ~/secrets
mountPoint: /custom/secrets
writable: true
```
> vm: propagate upstream support for mountPoint

- util/terminal/output.go
Observed the following when running colima in a terminal with somehow garbled settings (`stty size` printing `0 0`):
```
$ colima start
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0000] preparing network ...                         context=vm
INFO[0000] creating and starting ...                     context=vm
panic: runtime error: integer divide by zero
goroutine 25 [running]:
github.com/abiosoft/colima/util/terminal.(*verboseWriter).printScreen(0xc000172fc0)
github.com/abiosoft/colima/util/terminal/output.go:115 +0x1b3
github.com/abiosoft/colima/util/terminal.(*verboseWriter).refresh(0xc000172fc0)
github.com/abiosoft/colima/util/terminal/output.go:65 +0x92 …
```
> util: prevent division by zero in printScreen

- app/app.go
- cmd/start.go
- config/config.go
- embedded/defaults/colima.yaml
- environment/container/kubernetes/kubernetes.go
- environment/vm/lima/lima.go
vm: allow user to disable auto ssh config generation. Fixes #441 
k3s: fix Kubernetes version not persisting. Fixes #417 
vm: ignore running status when stopping and `--force` is passed. Fixes #439
> vm: multiple minor fixes

- cmd/start.go
- config/config.go
- environment/container/kubernetes/k3s.go
- environment/container/kubernetes/kubernetes.go
- environment/vm/lima/yaml.go
This PR adds a generic `--kubernetes-disable` flag which accepts a slice of names of packaged k3s components to disable.
Full list of those can be obtained by looking at the flags for `k3s server`:
```
--disable value                            (components) Do not deploy packaged components and delete any deployed components (valid items: coredns, servicelb, traefik, local-storage, metrics-server)
```
> feat: add kubernetes-disable flag

- environment/vm/lima/lima.go
RT
error log: 
```
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0000] preparing network ...                         context=vm
INFO[0000] starting ...                                  context=vm
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/abiosoft/colima/environment/vm/lima.includesHost({0xc000010900, 0xfb}, {0x1760f0f, 0x14}, {0xc0000bfe60, 0x10, 0x10})
github.com/abiosoft/colima/environment/vm/lima/lima.go:495 +0x216
```
> fix: when vm /etc/hosts contains empty line could cause index out of range

- environment/vm/lima/certs.go
I run colima behind a corporate VPN.
I was running into `x509 certificate signed by unknown authority` issues  and stumbled into [this](https://github.com/abiosoft/colima/issues/131) helpful issue. I followed the instructions [here](https://github.com/abiosoft/colima/issues/131#issuecomment-1034169701) and the problem did not resolve **until I manually copied the cert from `/etc/docker/certs.d` to `/etc/ssl/certs` within the VM**! This is just a guess, but maybe it's because I'm using containerd instead of docker as the container runtime.
Either way, having to ssh into the VM and manually copy a file doesn't seem like a scalable solution, which is why I'm submitting this PR. Completely amenable to feedback. Thank you for the amazing work you do. I ❤️ Colima.
> vm: add /etc/ssl/certs as certs copy target

- .github/workflows/golang-ci.yml
This change will resolve the warnings for usage GitHub actions deprecated commands `save-state` in golangci-lint workflow.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
> ci: upgrade golangci-lint GitHub action package from v2 to v3

- .github/workflows/go.yml
- .github/workflows/golang-ci.yml
- .github/workflows/integration.yml
Migrate CI workflows off of Node 12 by upgrading GitHub actions packages from v2 to v3.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
> ci: upgrade GitHub actions packages from v2 to v3

- app/app.go
- environment/container/kubernetes/k3s.go
- environment/container/kubernetes/kubernetes.go
This PR fixes an issue that the traefik component is still launched even it is disabled by default in the `colima.yaml` config.
On starting colima with kubernetes disabled, the kubernetes config is not persisted to the filesystem of the guest OS. Later we start the kubernetes and it failed to load the kubernetes config. As a side effect, it still launches the traefik component even it is disabled by default.
- Persist the kubernetes config to the filesystem of guest OS on starting colima
~~- Add traefik to the default disabled component list~~
> fix: persist kubernetes config

- cmd/start.go
- config/config.go
- embedded/defaults/colima.yaml
- environment/vm/lima/yaml.go
- util/yamlutil/yaml_test.go
This PR adds support for passing host resolver information to Lima, allowing the internal DNS resolver to resolve any custom names you wish. This is particularly useful for services that do not use `getaddrinfo`, ie. specific nginx, envoy configurations.
> dns: support for custom hosts

- cmd/start.go
- embedded/defaults/colima.yaml
- environment/vm/lima/yaml.go
- go.mod
- go.sum
> vm: bring back sshfs, workaround virtiofs

- cmd/root/root.go
I instinctively type `colima --version` because that works for almost all binaries, especially golang binaries, and it's easy to add with cobra.
This just adds the Version member of the root cobra.Command so we get `colima --version`.
```
$ _output/binaries/colima-Darwin-arm64  --version
colima version v0.5.2
```
> cli: add --version flag

- .github/workflows/integration.yml
- cmd/start.go
- config/configmanager/config.go
This is a start at config validation for
* #548
It's as far as I'll get right now, but it's a start. I'd rather add tests and such, but think I'll be lost on it for too long.
**Note that this does not allow empty values in config for vm-type, network-driver, mount-type, and those were previously allowed, but seemed to have unusual results in many cases.**
```
$ _output/binaries/colima-Darwin-arm64 start -p c --vm-type=xxx
FATA[0000] invalid vmType: 'xxx'
$ _output/binaries/colima-Darwin-arm64 start -p c --mount-type=xxx
WARN[0000] config load failed: invalid vmType: 'xxx'
WARN[0000] reverting to default settings
FATA[0000] invalid mountType: 'xxx'
$ _output/binaries/colima-Darwin-arm64 start -p c
WARN[0000] config load failed: invalid mountType: 'yyy'
WARN[0000] reverting to default …
```
> cli: basic validation of config flags and config file, fixes #548

- cmd/start.go
- config/config.go
- embedded/defaults/colima.yaml
- environment/vm/lima/yaml.go
- util/util.go
Fixes #554 
Possibly fixes #539
> vm: make rosetta emulation configurable

- README.md
Hi, I came across this project today and it's great, thank you!
It took me a while to figure out why `--vm-type=vz` wasn't using Rosetta by default in my Mac until I found the latest #555 PR.
Just updating a small bit in the docs in case it's useful for others. 
Thanks.
> docs: update README for Rosetta 2 emulation

- environment/container/docker/daemon.go
This PR intends to improve compatibility with docker desktop to simplify migration to colima.
https://docs.docker.com/engine/reference/commandline/dockerd/
> --host-gateway-ip ip 
> IP address that the special 'host-gateway' string in --add-host resolves to. Defaults to the IP address of the default bridge
Docker desktop sets this setting to `192.168.65.2` which is loopback address for vpnkit.
Fixes https://github.com/abiosoft/colima/issues/277
> docker: set host-gateway-ip to loopback interface

- app/app.go
- cmd/status.go
This PR adds the following details to `colima status` output:
- networkDriver
- cpu
- memory
- disk
Additional information is hidden behind the `--extended` flag.
Closes https://github.com/abiosoft/colima/issues/366.
> cli: add more details to status command

- app/app.go
This PR replaces the hardcoded `bash` used when logging into the ubuntu layer with `$SHELL`.
This is useful in case the user sets their login shell to a different shell, e.g. zsh or fish.
It also goes in line with the way that lima handles ssh login itself:
https://github.com/lima-vm/lima/blob/6ae40d3a25a6ffa006bbc04d0e8433357e756e8a/cmd/limactl/shell.go#L124-L129
> vm: respect `$SHELL` in `colima ssh` when `layer=true`

- environment/container/kubernetes/k3s.go
- environment/container/kubernetes/kubernetes.go
Attempting to start k3s 1.26.3 on colima with docker as container runtime results in a fatal kubelet error, preventing k3s from successfully starting.
```
time="2023-03-20T23:41:38Z" level=fatal msg="kubelet exited: failed to run Kubelet: validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///run/cri-dockerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
```
Not entirely sure whether this is the right thing to do, but [modern versions of k3s ship with an embedded version of cri-dockerd](https://github.com/k3s-io/k3s/blob/master/docs/adrs/cri-dockerd.md). Using this embedded version of cri-dockerd resolves the issue and k3s becomes usable after.
> k3s: use embedded cri-dockerd

- cmd/colima/main.go
- cmd/list.go
- environment/vm/lima/limautil/limautil.go
- fixes #680 
- utilise qemu stream arg for gvproxy
> chore: minor fixes

- colima.nix
While attempting to install colima via nix, I encountered the following error:
```
error: hash mismatch in fixed-output derivation '/nix/store/iz5w0f1hnjvh5w39q3gpiv10708188rl-colima-go-modules.drv':
specified: sha256-bEgC7j8WvCgrJ2Ahye4mfWVEmo6Y/OO64mDIJXvtaiE=
got:    sha256-lsTvzGFoC3Brnr1Q0Hl0ZqEDfcTeQ8vWGe+xylTyvts=
```
This change updates the hash to the correct hash indicated by the error output.
> nix: fix vendorSha256 in colima.nix

- config/dirs.go
This patch add some options for the location of user configuration directories.
As before, use `$HOME/.colima` if it already exists.
Otherwise, if the environment variable `XDG_CONFIG_HOME` is set, the Colima configuration directory should be (shell syntax) `"${XDG_CONFIG_HOME}"/colima`.
Likewise, if `XDG_CACHE_HOME` is set, then the cache should be in `"${XDG_CACHE_HOME}"/colima`.
If these variables are _not_ set, use the Go standard lib `os.UserConfigDir()` for the configuration:
-  `macOS  ` $HOME/Library/Application Support/colima
-  `Linux `  $HOME/.config/colima
- `Windows` %AppData%\colima
and uses `os.UserCacheDir()` for the cache:
-  `macOS  ` $HOME/Library/Caches/colima
-  `Linux `  $HOME/.cache/colima
- `Windows` %LocalAppData%\colima
This patch addresses …
> chore: use XDG base dir or platform dirs for config files. Fixes #483.

- .github/workflows/go.yml
- .github/workflows/golang-ci.yml
- .github/workflows/integration.yml
* Updated go versions used in workflows to 1.21
> ci: update go versions used in workflows to 1.21

- cmd/start.go
- config/config.go
- embedded/defaults/colima.yaml
- environment/vm/lima/yaml.go
This introduces a `--cgroups-v2` flag for `colima start` as a temporary stopgap for #764.
> vm: temporary workaround for #764

- daemon/daemon.go
From the Go specification (https://go.dev/ref/spec#For_range):
> "3. If the map is nil, the number of iterations is 0."
`len` returns 0 if the map is nil (https://pkg.go.dev/builtin#len). Therefore, checking `len(v) > 0` around a loop is unnecessary.
> chore: remove redundant `len` check

- core/core.go
The latest release of colima made it impossible to use a dev version of lima. This change allows the user to use a dev version but prints a warning.
> Allow dev version of lima

- environment/vm/lima/yaml.go
Attempt to fix the following error at boot:
```
Nov 17 14:24:04 colima systemd-hostnamed[1859]: Hostname set to <colima> (static)
Nov 17 14:24:04 colima cloud-init[1697]: LIMA| Executing /mnt/lima-cidata/provision.system/00000003
Nov 17 14:24:04 colima cloud-init[1697]: /mnt/lima-cidata/provision.system/00000003: 1: mkmntdirs: not found
Nov 17 14:24:04 colima cloud-init[1697]: LIMA| WARNING: Failed to execute /mnt/lima-cidata/provision.system/00000003
...
Nov 17 14:24:04 colima cloud-init[1697]: Cloud-init v. 23.3.1-0ubuntu2 finished at Fri, 17 Nov 2023 14:24:04 +0000. Datasource DataSourceNoCloud [seed=/dev/vdb][dsmode=net].  Up 5.89 seconds
Nov 17 14:24:04 colima systemd[1]: cloud-final.service: Main process exited, code=exited, status=1/FAILURE
Nov 17 14:24:04 colima systemd[1]: …
```
> vm: do not call mkmntdirs, it does not exists

- cmd/prune.go
- environment/vm/lima/dependencies.go
- environment/vm/lima/lima.go
- environment/vm/lima/limautil/limautil.go
This adds `prune` command to clear downloaded assets.
```
colima prune --help                                                                                                                            administrator@50029
Prune cached downloaded assets
Usage:
colima prune [flags]
Flags:
-a, --all     include Lima assets
-f, --force   do not prompt for yes/no
-h, --help    help for prune
Global Flags:
-p, --profile string   profile name, for multiple instances (default "default")
-v, --verbose          enable verbose log
--very-verbose     enable more verbose log
```
> cli: add prune command

- environment/container/containerd/containerd.go
- environment/container/docker/docker.go
- environment/vm/lima/deb/deb.go
- environment/vm/lima/deb/docker.go
- environment/vm/lima/deb/mantic.go
- environment/vm/lima/dependencies.go
> docker: use docker-ce packages

- environment/vm/lima/deb/docker.go
Without purging, packages not fully removed (e.g. dpkg -l will still show the packages).
> vm: purge packages instead of just removing them

- .github/workflows/integration.yml
- embedded/defaults/colima.yaml
- environment/vm/lima/deb/mantic.go
"htop", "vim", "inetutils-ping", "dnsutils" are optional dependencies - only required for developers working on colima.
I'd like to get some feedback on possibly moving these packages out of the main codebase into the configuration file. This would enable developers removing these packages without patching colima core source code.
Thanks !
> vm: do not require optional system utilities

- environment/vm/lima/deb/mantic.go
See https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#depends for the definition of Recommended packages.
Not installing Recommended packages makes the generation more controllable and predictable.
Currently, in practice as an example docker-ce will no longer install docker-ce-rootless-extras .
> vm: do not install recommended packages

- environment/vm/lima/yaml.go
See https://github.com/ddev/ddev/issues/4466 .
Is this workaround still needed in colima ?
> vm: remove virtiofs workaround

- environment/vm/lima/deb/docker.go
I have a use case where I would need to specify the docker version/channel to install. This is related to a GitHub Action I maintain https://github.com/crazy-max/ghaction-setup-docker and specially https://github.com/crazy-max/ghaction-setup-docker/issues/47.
With this change, user can set `DOCKER_INSTALL_VERSION` and `DOCKER_INSTALL_CHANNEL` to install a specific version. This also returns the right `pkgFiles` based on the selected channel.
> docker: allow specifying version and channel to install

- environment/container/docker/daemon.go
- environment/container/docker/docker.go
> docker: move host-gateway-ip config to systemd

- embedded/defaults/colima.yaml
Bumping k3s template version to avoid confusion as in https://github.com/abiosoft/colima/discussions/945
> k3s: Update default template version

- environment/vm/lima/yaml.go
Security update to fix the following CVEs.
- [CVE-2024-21626](https://github.com/opencontainers/runc/security/advisories/GHSA-xr7r-f8xq-vfvv)
- [CVE-2024-23650](https://github.com/moby/buildkit/security/advisories/GHSA-9p26-698r-w4hx)
- [CVE-2024-23651](https://github.com/moby/buildkit/security/advisories/GHSA-m3r6-h7wv-7xxv)
- [CVE-2024-23652](https://github.com/moby/buildkit/security/advisories/GHSA-4v98-7qmw-rqr8)
- [CVE-2024-23653](https://github.com/moby/buildkit/security/advisories/GHSA-wr6v-9f75-vh2g)
- [CVE-2024-24557](https://github.com/moby/moby/security/advisories/GHSA-xw73-rw38-6vjc)
> core: update disk images

- environment/container/docker/daemon.go
The current Colima VM (Ubuntu) is using the default value of 1024 file descriptors. This is insufficient for software such as Kafka that requires a high amount of open files, even in development environments.
https://docs.confluent.io/platform/current/kafka/deployment.html#file-descriptors-and-mmap
Since the principal purpose of the Colima VM is just to run docker, this sets the value to infinity to limit to the OS limits.
> docker: Increase ulimit to infinity

- environment/container/containerd/containerd.go
- environment/vm/lima/yaml.go
Small patch to expose the `containerd` socket to the host in similar fashion to how the Docker socket gets exposed.
> containerd: add socket forwarding to host

- docs/FAQ.md
Although most people won't run into the issue as they're probably mapping volumes from their `/Users/<username>` directory, I think this information would be handy for anyone running into the issue of docker bind mounts showing up empty on the container. This was the issue I faced in https://github.com/abiosoft/colima/issues/1051 and it took me 1-2 days to solve it.
> docs: update faq regarding docker bind mount issue

- cmd/start.go
Hello! I'm creating this to ensure that the `--vm-type` flag is being respected. I understand that at one point qemu had issues on M3 chips, however in my current company we're experiencing issues using `vz`. As such, we've had to revert back to `qemu`, and it's worked a treat.
To get it going currently we need to run `coilima start --edit`, which is fine for testing, but being able to run start with qemu defined as the vm type **and** have that setting respected would be a game changer. Happy to work on this and improve if needed, but I think this should do the trick.
> core: ensure that the user defined `VMType` flag is respected for m3 devices

- cmd/start.go
This removes the special case logic for M3 macs that use the vz driver instead of qemu. A lot of people are having trouble with vz on M3 macs:
- https://github.com/abiosoft/colima/issues/987#issuecomment-1999938930
- https://github.com/abiosoft/colima/pull/1045#issue-2363549238
- https://github.com/abiosoft/colima/issues/985#issue-2132482350
- https://github.com/abiosoft/colima/issues/985#issuecomment-2024729107
- https://github.com/abiosoft/colima/issues/985#issuecomment-1987058790
> core: revert to using qemu by default on M3 macs

- config/dirs.go
- docs/FAQ.md
- embedded/defaults/colima.yaml
currently, colima configs get autopopulated in `$HOME/.colima`, this addition would allow users to set a `$COLIMA_HOME` environment variable to change this location if users have other preferences (i personally prefer all my program configs go in `$HOME/.config/{app_name}`)
I didn't see any information on contributing to this repo, but did see the hefty issue backlog i wouldn't want to make even bigger, so i thought it'd be ok to make a small PR myself! no worries if people see this change as unnecessary and decide to close it out tho
> core: add support for COLIMA_HOME env var

- environment/vm/lima/lima.go
- environment/vm/lima/network.go
- environment/vm/lima/yaml.go
- util/util.go
> net: support forwarding to specific host IP addresses

- environment/container/docker/daemon.go
- environment/container/docker/docker.go
The initialization sequence is:
(1) VM boot
(2) Write daemon configuration
When the VM boot, the Docker systemd service is started, so the new configuration is not picked up until the next VM boot.
To fix this, reload the systemd daemon config (to pick up the systemd service file written by `addHostGateway`) and then restart the Docker systemd service, which will use the new systemd unit file as well as any customizations to `daemon.json`.
* #834
* #1060
(My specific issue was that my `daemon.json` customizations in the `docker` section of `colima.yaml` were not being applied on first boot.)
> fix(docker): apply configuration on first boot

- util/downloader/download.go
Fixes #1098.
The downloader currently has undesired behaviour of downloading twice when fetching the possible redirect URL of the asset to be downloaded.
This resolves it by ensuring the initial request is an HEAD request.
> core: fix downloader duplicating downloads

- Makefile
- https://github.com/abiosoft/colima/issues/1106
This pull request fixes checksums of assets for macOS.
From colima v0.7.1, assets for macOS are signed by codesign.
- https://github.com/abiosoft/colima/commit/3415501d7d1977390c844f16639d2011817ad468
- https://github.com/abiosoft/colima/pull/1094
But due to this checksums became invalid.
```console
$ gh release download abiosoft/colima v0.7.1
$ cat *.sha256sum
9db4f5617eb3a16ef4abca4d515a7e81b80f7f8646a8c3fe50e4eb6e6e1a8ccb *colima-Darwin-arm64
e136336f3b000fda729f4266d1af573dcf3378568d4c5433c6b63350f960f296 *colima-Darwin-x86_64
f866550da41a4d1df7437fbf2e42449e213281ac1784d2f4d905e7bd13c5c772 *colima-Linux-aarch64
95cdef8ffc9fa2620a9a4c0771c4eab727b5d654341a0b6fcc70842c2bc38486 *colima-Linux-x86_64
$ sha256sum colima-Darwin-arm64 …
```
> chore: generate checksum files after signing assets by codesign

- environment/vm/lima/certs.go
Currently, colima would copy self-signed root CA certs from the `~/.docker.certs.d/` directory to the VM. This allows docker daemon in the VM to pull from registries that are signed with a self-signed cert. 
However, when removing certs from the `~/.docker/certs.d` directory, they would not be removed from the VM. More confusingly, even after running `colima delete && colima start`, the same custom certs are still present in the newly created VM. 
This PR would first delete the intermediate cache directory prior to copying the certs from `~/.docker/certs.d`, which should resolve the certs persistence across colima deletion/creation. 
Note that certs will still be persisted across colima restart, since they are still present in the VM. While we can simply remove all certs from …
> docker: remove cert cache directory before copying host certs

- cmd/delete.go
We have observed some users not realizing container data is lost when doing delete. This change does not modify scripted behaviour, as -f / force toggles maintains same logic.
> chore: add second confirmation for container data loss

- app/app.go
- cmd/start.go
- config/configmanager/configmanager.go
- environment/vm/lima/lima.go
- environment/vm/lima/limautil/instance.go
- environment/vm/lima/network.go
- util/osutil/os.go
This introduces a new `--save-config` flag which defaults to true.
To prevent Colima from overriding configuration settings, `--save-config=false` should be specified for `colima start`.
As an alternative option, `COLIMA_SAVE_CONFIG=0` environment variable can be set.
Fixes #613.
> config: make persistence optional with --save-config flag

- environment/vm/lima/certs.go
Added force argument to avoid an issue where the directory does not exist yet.
Fixes #1128
> docker: avoid error where the cache docker-certs directory does not exist

- README.md
Fixed typo on Apple Silicon on README
> docs: fixed typo on Apple Silicon in README

- .github/workflows/integration.yml
- environment/container/docker/daemon.go
- Automatically replace 127.0.0.1 with host gateway ip in docker daemon.json proxy settings
- Refactored daemon.json to move fetching of gateway ip to a function for DRY
Fixes #1144
Related to #956, #1040
> docker: replace 127.0.0.1 with host gateway ip in docker daemon.json proxy settings

- app/app.go
- cmd/root/root.go
- cmd/update.go
- environment/container.go
- environment/container/containerd/containerd.go
- environment/container/docker/docker.go
- environment/container/incus/config.yaml
- environment/container/incus/incus.go
- environment/container/kubernetes/kubernetes.go
- util/debutil/debutil.go
This introduces the `colima update` command to update the container runtime version without requiring a new version of Colima.
```
$ colima update --help
Update the current container runtime.
Usage:
colima update [profile] [flags]
Aliases:
update, u, up
Flags:
-h, --help   help for update
Global Flags:
-p, --profile string   profile name, for multiple instances (default "default")
-v, --verbose          enable verbose log
--very-verbose     enable more verbose log
```
> cli: add update command

- environment/vm/lima/lima.go
> core: retain SSH port forwarder

- app/app.go
- cmd/status.go
Adds the option of JSON output to the status command, which would be useful for me, and possibly others.
> cli: add --json flag to status command

- cmd/start.go
- config/config.go
- environment/vm/lima/yaml.go
colima start --cpu 1 --memory 0.8 --disk 10
> config: ability to specifying memory in decimal GiB

- environment/vm/lima/limautil/files.go
- environment/vm/lima/limautil/instance.go
- environment/vm/lima/network.go
> net: clear assets directory on startup

- environment/vm/lima/limaconfig/config.go
- environment/vm/lima/limautil/network.go
- environment/vm/lima/yaml.go
> net: set route for external address

- cmd/start.go
- config/config.go
- config/configmanager/configmanager.go
- embedded/defaults/colima.yaml
- environment/vm/lima/lima.go
- environment/vm/lima/limautil/image.go
- util/downloader/download.go
- util/downloader/sha.go
This PR adds support for specifying a disk image on the local disk. 
Users can now manually download the Colima disk image and specify the path to the downloaded file.
```
colima start --disk-image ~/Downloads/ubuntu-24.04-minimal-cloudimg-arm64-docker.qcow2
```
> vm: add support for custom disk images

- .golangci.yml
- app/app.go
- environment/container/docker/daemon.go
- environment/container/kubernetes/kubernetes.go
- util/terminal/output.go
and fix code according gocritic advices
> ci: enable gocritic in golangci

- docs/FAQ.md
Calling out potential need to update Docker client configuration along with colima configuraiion changes.
> faq: update to address potential need for Docker client configuration

- cmd/start.go
```
change fixes quotation error in colima start command for k3s-arg flag
```
issue https://github.com/abiosoft/colima/issues/1229
> cli: add quotes to k3s-arg example for colima start

- LICENSE
This reverts commit 431146a84d9100e9866762cc621ea64bdbc8a16c. (deleted pr: https://github.com/abiosoft/colima/pull/1235)
Copyright years are not to be updated.
https://courier.unesco.org/en/articles/universal-copyright-convention
> It prescribes that the formalities required by the national law of a contracting state shall be considered to be satisfied if all the copies of a work originating in another contracting state carry the symbol ©, accompanied by the name of the copyright owner and **the year of first publication**.
The person who made this change, @JasonnnW3000, had [created other similar Pull Requests for other famous OSS project](https://github.com/orgs/community/discussions/148296). Therefore, it appears that the account is currently suspended and deleted pull request.
> chore: fix copyright license year (Revert #1235)

- environment/vm/lima/config.go
- environment/vm/lima/file.go
```
change logs actual error when trying to read Colima config file
```
Issue can be found [here](https://github.com/abiosoft/colima/issues/1239).
> chore: log possible error while reading config file

- util/downloader/sha.go
> core: use native shasum binary on macOS for download verification

- environment/container/kubernetes/kubernetes.go
According to facing the error while using the `containerd` as runtime and enable `kubernetes` features as the following:
```
FATA[0018] error provisioning kubernetes: error at 'downloading and installing': error downloading 'https://github.com/k3s-io/k3s/releases/download//k3s': error validating SHA sum for 'k3s': exit status 1 
```
It turns out missing `version` string in baseURL which goes with `environment/container/kubernetes/k3s.go`
Thus make a if-else statement for setup `DefaultVersion` which declares in `environment/container/kubernetes/kubernetes.go`
> core: config initial value for kubernetes version if empty in yaml

- environment/container/kubernetes/kubernetes.go
As subject mentioned, just a small change updating the default version string.
> k8s: update latest version for default kubernetes release

- environment/container/incus/config.yaml
The purpose of specifying the `core.https_address` by default is to expose the Web UI. 
However, from Incus 6.7, the Web UI is accessible with the `incus webui` command.
> incus: remove core.https_address from default config

- environment/container/docker/daemon.go
> revert: "docker: fix cgroupdriver"

- cli/command.go
- util/fsutil/fs.go
As illustrated in issue #1319, the second prompt for the delete command uses a bold + red format mode using escape codes. However, this mode is not reset at the end and ends up leaking unto next lines on the terminal.
This change will make sure all `question` strings passed to the `Prompt` function will be closed properly by a reset escape sequence.
Includes a fmt change too.
Before:
After:
> Properly reset formatting at the end of question prompts

- go.mod
The PR tidies up dependencies in `go.mod` by splitting `require` into two sections:
1) direct dependencies;
2) indirect dependencies.
> chore: reorganize dependencies in go.mod

- environment/vm/lima/lima.go
- environment/vm/lima/limaconfig/config.go
- environment/vm/lima/yaml.go
Should fix #1292 and fix #1300, and maybe others
gRPC port forwarder is considered stable in lima, no need to force older SSH forwarder by default
> vm: support UDP port forwarding

- environment/container/docker/daemon.go
This improves PR #1145 by replacing any loopback address, not only _127.0.0.1_ but also _localhost_ with the host gateway.
In my case my proxy is configured as localhost, and it listens both on 127.0.0.1 (IPv4) and ::1 (IPv6).
The implementation logic is the same as in [lima](https://github.com/lima-vm/lima/blob/0625d0b084450e874869dcbc9f63d4312797c3fe/pkg/cidata/cidata.go#L73).
This addresses issue #956.
In my opinion in _no-proxy_ env variable references to localhost should not be replaced, because in this case it refers to the loopback of the container.
> docker: replace also localhost with host gateway ip in docker daemon.json

- environment/container/kubernetes/kubeconfig.go
Currently when starting a vm + k8s cluster the kubeconfig is always written to "~/.kube/config" which is the default path. By defining the env variable "KUBECONFIG" it is possible to override the default path. This does currently not apply to colima.
As it is possible to configure multiple locations with "KUBECONFIG" I opted to always use the first configured one as the location to save the config.
> k3s: write kubeconfig to KUBECONFIG defined file

- environment/vm/lima/file.go
Potential fix for [https://github.com/abiosoft/colima/security/code-scanning/7](https://github.com/abiosoft/colima/security/code-scanning/7)
To fix the problem, we should ensure that the value parsed from `stats[1]` is within the valid range for `fs.FileMode` (i.e., between 0 and `math.MaxUint32`) before converting it. We should also handle errors from `strconv.Atoi` to avoid using invalid values. The best way to do this is to use `strconv.ParseUint` with a bit size of 32, which will only succeed for valid, non-negative values within the range of a `uint32`. If parsing fails or the value is out of bounds, we should return an error or a default value. The changes are needed in the anonymous function assigned to `info.mode` in the `newFileInfo` function (lines 60-63). We also need to import …
> Potential fix for code scanning alert no. 7: Incorrect conversion between integer types

- cmd/start.go
New instances created uses `sshfs` as the default mount type when vz is in use.
This PR fixes that to use virtiofs as the default mount type for vz.
> cli: set default mount type to virtiofs for vz

- cmd/start.go
- config/config.go
- environment/vm/lima/lima.go
> vm: fix binfmt not enabled after restart

- environment/container/kubernetes/k3s.go
When networking is enabled but the interface does not have any IP assigned yet, k3s installation can fail. The `IPAddress` function says that it is guaranteed to return a value, which is technically true, but that value can be an empty string if the network interface exists but doesn't have any IP assigned.
This changes the k3s installation to wait for up to 20 seconds for an address to be assigned before failing.
Fixes #1373
> k3s: retry ip address retrieval during setup

- config/config.go
- docs/FAQ.md
- embedded/defaults/colima.yaml
- environment/vm/lima/yaml.go
The `/tmp/colima` directory is mounted by default but it is hardly used.
Also it is problematic when there are multiple users on the machine and Colima is being used by both users, folder permission issues may prevent Colima from starting for one of the users.
This PR removes the `/tmp/colima` from the default mount and limits it only to the $HOME directory.
> chore: remove tmp mount

- cmd/start.go
This PR reinstates the previous behaviour of loading config from the template file (when present).
Template use can still be disabled with `colima start --template=false`.
> cli: default template flag to true.

- cmd/daemon/cmd.go
- cmd/start.go
- config/config.go
- daemon/daemon.go
- daemon/process/inotify/volumes.go
- daemon/process/vmnet/vmnet.go
- embedded/defaults/colima.yaml
- embedded/network/sudo.txt
- environment/vm/lima/daemon.go
- environment/vm/lima/dns.go
- environment/vm/lima/yaml.go
This PR adds support for bridge mode networking.
Resolves #879, #636
```
colima start --network-address --network-mode bridged
```
The `--network-interface` flag can be used to specify a different network interface to use on the host. It defaults to `en0` if not set.
```
colima start --network-address --network-mode bridge --network-interface en0
```
- Requires root access initially to setup network requirements. Colima will prompt for sudo password.
> net: add support for bridged mode

- environment/vm/lima/lima.go
> vm: enable 386 emulation regardless of rosetta
